name: CI/CD Pipeline - Expensy

on:
  push:
    branches:
      - main   # Se ejecuta cuando pushes a la rama main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 3. Build & Push Backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./expensy_backend
          push: true
          tags: aclota/expensy-backend:latest

      # 4. Build & Push Frontend
      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./expensy_frontend
          push: true
          tags: aclota/expensy-frontend:latest
